--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2023-04-16 13:26:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3326 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 49190)
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    account_id integer NOT NULL,
    balance bigint DEFAULT '0'::bigint NOT NULL
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 49189)
-- Name: accounts_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 49198)
-- Name: operations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operations (
    account_id integer NOT NULL,
    operation_id bigint NOT NULL,
    operation_type integer NOT NULL,
    operation_amount bigint NOT NULL,
    sender_id integer,
    "timestamp" timestamp without time zone
);


ALTER TABLE public.operations OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 49213)
-- Name: operations_operation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operations ALTER COLUMN operation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operations_operation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 49214)
-- Name: operations_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.operations_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.operations_seq OWNER TO postgres;

--
-- TOC entry 3317 (class 0 OID 49190)
-- Dependencies: 210
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (account_id, balance) FROM stdin;
2	4545575
1	318477
\.


--
-- TOC entry 3318 (class 0 OID 49198)
-- Dependencies: 211
-- Data for Name: operations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operations (account_id, operation_id, operation_type, operation_amount, sender_id, "timestamp") FROM stdin;
2	1603	3	9	1	\N
2	1652	3	9	1	2023-04-16 00:42:30.917632
1	1653	0	0	1	\N
2	1654	0	0	2	\N
2	1702	0	0	2	2023-04-16 00:45:10.337088
1	1703	0	0	1	2023-04-16 00:45:37.122126
\.


--
-- TOC entry 3327 (class 0 OID 0)
-- Dependencies: 209
-- Name: accounts_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_account_id_seq', 1, false);


--
-- TOC entry 3328 (class 0 OID 0)
-- Dependencies: 212
-- Name: operations_operation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operations_operation_id_seq', 1, false);


--
-- TOC entry 3329 (class 0 OID 0)
-- Dependencies: 213
-- Name: operations_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operations_seq', 1751, true);


--
-- TOC entry 3172 (class 2606 OID 49195)
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);


--
-- TOC entry 3174 (class 2606 OID 49202)
-- Name: operations operations_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_pk PRIMARY KEY (operation_id);


--
-- TOC entry 3175 (class 2606 OID 49203)
-- Name: operations operations_accounts_account_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_accounts_account_id_fk FOREIGN KEY (account_id) REFERENCES public.accounts(account_id);


--
-- TOC entry 3176 (class 2606 OID 49208)
-- Name: operations operations_accounts_account_id_fk2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_accounts_account_id_fk2 FOREIGN KEY (sender_id) REFERENCES public.accounts(account_id);


-- Completed on 2023-04-16 13:26:41

--
-- PostgreSQL database dump complete
--

